metadata:
  name: hw4prod
  labels:
    app: frontapp
spec:
  rules:
  - http:
      paths:
      - path: /frontapp
        pathType: Prefix
        backend: 
          service:
            name: frontapp
            port:
              number: 8080
