namespace: hw4-prod
commonLabels:
  training: block4
resources:
  - ingress.yaml
patches:
- path: patch_replicacount_backapp.yaml
- path: patch_replicacount_frontapp.yaml
- target:
    kind: Ingress
    name: hw4-prod
  patch: |-
    - op: add
      path: /spec/rules/0/host
      value: application.cubix.localhost
