namespace: hw4-prod
resources:
  - deployment_frontapp.yaml
  - deployment_backapp.yaml
  - service_frontapp.yaml
  - service_backapp.yaml
  - ingress.yaml
patches:
  - target:
      kind: Ingress
      name: hw4prod
    patch: |-
      - op: add
        path: /spec/rules/0/host
        value: application.cubix.localhost