apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontapp
  labels:
    app: frontapp
    homework: frontapp
spec:
  selector:
    matchLabels:
      app: frontapp
      homework: frontapp
  template:
    spec:
      containers:
      - name: frontapp
        env:
        - name: JAVA_OPTS
          value: ""