apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw4backapp
  labels:
    app: backapp
    homework: backapp
spec:
  selector:
    matchLabels:
      app: backapp
      homework: backapp
  template:
    spec:
      containers:
      - name: backapp
        env:
        - name: JAVA_OPTS
          value: -Dspring.main.banner-mode=on