apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontapp
  labels:
    app: frontapp
    training: block4
    homework: frontapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontapp
  template:
    metadata:
      labels:
        app: frontapp
        training: block4
        homework: frontapp
    spec:
      containers:
      - name: afrontapp
        image: quay.io/drsylent/cubix/block3/homework-frontapp:springboot3
        ports:
        - containerPort: 8080
        env:
        - name: APP_DEFAULT_MESSAGE
          value: "frontapp"
        - name: JAVA_OPTS
          value: ""
        - name: BACK_URL
          value: http://backapp:8080