namespace: hw4-base
commonLabels:
  training: block4
resources:
  - deployment_frontapp.yaml
  - deployment_backapp.yaml
  - service_frontapp.yaml
  - service_backapp.yaml
  - ingress.yaml
patches:
- path: patch_replicacount_backapp.yaml
- path: patch_replicacount_frontapp.yaml
- path: patch_springboothead_frontapp.yaml
- path: patch_springboothead_backapp.yaml
- path: patch_backapp_var.yaml
- path: patch_frontapp_var.yaml

