commonLabels:
  training: block4
resources:
  - deployment_frontapp.yaml
  - deployment_backapp.yaml
  - service_frontapp.yaml
  - service_backapp.yaml
  - ingress.yaml
patches:
- path: patch-replicacount.yaml
- path: patch-springbootheader.yaml
- path: patch_backapp_var.yaml
- path: patch_frontapp_var.yaml

